# Generated by Django 4.0.1 on 2022-02-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(max_length=200, upload_to='carousel/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('query', models.TextField()),
                ('file', models.FileField(upload_to='contactus/')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('img', models.ImageField(max_length=200, upload_to='Statisticdept Gallery/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LatestDept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='lastestdept update/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='McaAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='upload date')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('file', models.FileField(upload_to='mca admission/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='McaCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='McaEbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('writer', models.CharField(max_length=200)),
                ('file', models.FileField(max_length=200, upload_to='mca ebook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='McaNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='upload date')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('file', models.FileField(upload_to='mca notice/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='McaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='upload date')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('file', models.FileField(upload_to='mca results/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='McaSemister1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('file', models.FileField(max_length=200, upload_to='mca questions/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='McaSemister2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('file', models.FileField(max_length=200, upload_to='mca questions/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='McaSemister3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('file', models.FileField(max_length=200, upload_to='mca questions/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='McaSemister4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('file', models.FileField(max_length=200, upload_to='mca questions/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='McaSemister5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('file', models.FileField(max_length=200, upload_to='mca questions/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='McaSemister6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('file', models.FileField(max_length=200, upload_to='mca questions/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='McaSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='upload date')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('file', models.FileField(upload_to='statistic admission/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticEbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('writer', models.CharField(max_length=200)),
                ('file', models.FileField(max_length=200, upload_to='statistic ebook/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='upload date')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('file', models.FileField(upload_to='statistic notice/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='upload date')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('file', models.FileField(upload_to='statistic results/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticSemister1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('file', models.FileField(max_length=200, upload_to='statistic questions/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticSemister2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('file', models.FileField(max_length=200, upload_to='statistic questions/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticSemister3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('file', models.FileField(max_length=200, upload_to='statistic questions/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticSemister4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('file', models.FileField(max_length=200, upload_to='statistic questions/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticSemister5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('file', models.FileField(max_length=200, upload_to='statistic questions/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticSemister6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('file', models.FileField(max_length=200, upload_to='statistic questions/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticsSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=200)),
                ('img', models.ImageField(max_length=200, upload_to='studentblog Gallery/')),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticsFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('experience', models.PositiveIntegerField()),
                ('img', models.ImageField(max_length=200, upload_to='mcafaculty/')),
                ('administrative_post', models.CharField(max_length=300)),
                ('qualification', models.ManyToManyField(to='mca.Qualification')),
                ('subject', models.ManyToManyField(to='mca.StatisticsSubject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='McaFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('experience', models.PositiveIntegerField()),
                ('img', models.ImageField(max_length=200, upload_to='mcafaculty/')),
                ('qualification', models.ManyToManyField(to='mca.Qualification')),
                ('subject', models.ManyToManyField(to='mca.McaSubject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
