# Generated by Django 4.0.1 on 2022-02-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcaebook',
            name='file',
            field=models.FileField(max_length=200, upload_to='mca ebook/'),
        ),
    ]
